server:
  port: 8081
spring:
  application:
    name: front
  web:
    resources:
      cache:
        periods: 0
      chain:
        cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

blog:
  api:
    post-url: http://localhost:8083/posts